# Generated by Django 5.1.6 on 2025-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
