# Generated by Django 5.1.6 on 2025-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Investor', 'Investor'), ('Startup', 'Startup'), ('Mentor', 'Mentor')], max_length=20, null=True),
        ),
    ]
