# Generated by Django 5.1.6 on 2025-03-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_who_are_you'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Investor', 'Investor'), ('Startup', 'Startup')], max_length=20, null=True),
        ),
    ]
