# Generated by Django 5.1.6 on 2025-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_who_are_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Startup', 'Startup'), ('Investor', 'Investor')], max_length=20, null=True),
        ),
    ]
