# Generated by Django 5.1.6 on 2025-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_who_are_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='privacy_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Startup', 'Startup'), ('Investor', 'Investor')], max_length=20, null=True),
        ),
    ]
