# Generated by Django 5.1.6 on 2025-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contact_who_are_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Investor', 'Investor'), ('Startup', 'Startup')], max_length=20, null=True),
        ),
    ]
