# Generated by Django 5.1.6 on 2025-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_bookspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('Investor', 'Investor'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], max_length=20, null=True),
        ),
    ]
