# Generated by Django 5.1.6 on 2025-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Startup', 'Startup'), ('Investor', 'Investor'), ('Mentor', 'Mentor')], max_length=20, null=True),
        ),
    ]
