# Generated by Django 5.1.6 on 2025-02-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_content',
            new_name='content',
        ),
    ]
