# Generated by Django 5.1.6 on 2025-02-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_content',
            field=models.TextField(blank=True),
        ),
    ]
