# Generated by Django 5.1.6 on 2025-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
