# Generated by Django 5.1.6 on 2025-02-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('First Revenue', 'First Revenue'), ('Scaling', 'Scaling')], max_length=100, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('amount_raising', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='authentication.companytag')),
            ],
        ),
    ]
