# Generated by Django 5.1.6 on 2025-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Investor', 'Investor'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], max_length=10)),
                ('about_you', models.TextField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
