# Generated by Django 5.1.6 on 2025-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
