# Generated by Django 5.1.6 on 2025-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_company_about_startup_company_checkmark1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyteam',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='authentication.companyteam'),
        ),
    ]
