# Generated by Django 5.1.6 on 2025-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_is_activated_users_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organization_logo',
            field=models.FileField(blank=True, null=True, upload_to='organization_logos/'),
        ),
    ]
