# Generated by Django 5.1.6 on 2025-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organization_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
