# Generated by Django 5.1.6 on 2025-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
