# Generated by Django 5.1.6 on 2025-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_users_organization_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='about_you',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Employee', 'Employee')], max_length=10),
        ),
    ]
