# Generated by Django 5.1.6 on 2025-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_users_about_you_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organization_role',
            field=models.CharField(choices=[('Investor', 'Investor'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
