# Generated by Django 5.1.6 on 2025-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_users_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('Investor', 'Investor'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], max_length=10, null=True),
        ),
    ]
