# Generated by Django 5.1.6 on 2025-03-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_users_organization_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Employee', 'Employee')], max_length=10, null=True),
        ),
    ]
