# Generated by Django 5.1.6 on 2025-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('Investor', 'Investor'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], default='Startup', max_length=10, null=True),
        ),
    ]
