# Generated by Django 5.1.6 on 2025-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_users_organization_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='investment_interest_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
