# Generated by Django 5.1.6 on 2025-08-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='participating_status',
            field=models.CharField(blank=True, choices=[('investor', 'investor'), ('startup', 'startup')], max_length=20, null=True),
        ),
    ]
