# Generated by Django 5.1.6 on 2025-08-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_cohort_participating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
