# Generated by Django 5.1.6 on 2025-08-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_alter_cohort_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
