# Generated by Django 5.1.6 on 2025-02-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='file',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='video_link',
        ),
        migrations.AddField(
            model_name='academy',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='chapter_logos/'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='academy_files/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academy.academy')),
            ],
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
