# Generated by Django 5.1.6 on 2025-02-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_academy_chapter_remove_academy_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='chapter',
            new_name='academy',
        ),
    ]
