# Generated by Django 5.1.6 on 2025-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_rename_chapter_article_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
