# Generated by Django 5.1.6 on 2025-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
