# Generated by Django 5.1.6 on 2025-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='documents',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
